spring:
  rabbitmq:
     host: 192.168.9.100
     port: 5672
     username: reindex
     password: reindex
     listener:
       simple:
         retry:
           enabled: true
           max-attempts: 5

  datasource:
    hikari:
      st:
        name: st
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.9.100:3306/tongyun_mes?useSSL=false
        password: fhieukzjdhwuieurwuiery19dakjdJHNMJQ
        username: gerp_mes
        port: 3306
      jh:
        name: jh
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.9.45:3306/tongyun_mes?useSSL=false
        password: tongyun2017
        username: shengtian
        port: 3306
      sd:
        name: sd
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.9.32:3306/tongyun_mes?useSSL=false
        username: shengtian
        password: evMyV0X5EhlPS4545BmaNYmE
        port: 3306
      sda:
        name: sd
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.100:3306/tongyun_mes?useSSL=false
        username: shengtian
        password: evMyV0X5EhlPS4545BmaNYmE
        port: 3306
      sh:
        name: sh
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.2.100:3306/tongyun_mes?useSSL=false
        username: root
        password: root
        port: 3306
      dx:
        name: dx
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.5.100:3306/tongyun_mes?useSSL=false
        username: gerptodaxing
        password: evMyV0X5EhlPS4545BmaNYmE
  redis:
    host: 192.168.9.100
    port: 6379
    password: wP35CBv7HrxyYDkfeqUqbfKSMcsQWoXNT
    database: 14

mq:
    config:
        exchange: car.direct
        queue:
            send: car.send
            send.routing.key: car.send.routing.key
            cancel: car.cancel
            cancel.routing.key: car.cancel.routing.key
            ready: car.ready
            ready.routing.key: car.ready.routing.key


wx:
  appid: wx4f5eaae5d35613f8
  secret: df3a6a381a83411f092829634abeafc4
  templateId: k_Q0SEtmAFNW-YamXjpLOjZXZBd7NoEkvbpPIRJ3hvE