spring:
  rabbitmq:
     host: 139.129.252.208
     port: 5672
     username: reindex
     password: fH7MtSCKQeY
     listener:
       simple:
         retry:
           enabled: true
           max-attempts: 5

  datasource:
    hikari:
      st:
        name: st
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://rrds6w668056ajs86v72f.mysql.rds.aliyuncs.com:3306/gerp_c_mes?useSSL=false
        username: gerp
        password: yAMxZGKVEYRU3qPpcmsrBf6vXH4L5njC
        port: 3306
      jh:
        name: jh
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://rm-m5egj8m3y952pf6e9.mysql.rds.aliyuncs.com:3306/gerp_mes_app_a?useSSL=false
        username: gerp
        password: wcyGke4tWDRxiBdsp2b6TAfzNrL123Fn
        port: 3306
      sd:
        name: sd
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://rm-m5egj8m3y952pf6e9.mysql.rds.aliyuncs.com:3306/gerp_mes_app_a?useSSL=false
        username: gerp
        password: wcyGke4tWDRxiBdsp2b6TAfzNrL123Fn
        port: 3306
      sda:
        name: sda
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://rm-m5egj8m3y952pf6e9.mysql.rds.aliyuncs.com:3306/gerp_c_mes?useSSL=false
        username: gerp
        password: wcyGke4tWDRxiBdsp2b6TAfzNrL123Fn
        port: 3306
      sh:
        name: sh
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://rm-m5egj8m3y952pf6e9.mysql.rds.aliyuncs.com:3306/gerp_c_mes?useSSL=false
        username: gerp
        password: wcyGke4tWDRxiBdsp2b6TAfzNrL123Fn
        port: 3306
      dx:
        name: dx
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://rm-m5egj8m3y952pf6e9.mysql.rds.aliyuncs.com:3306/gerp_c_mes?useSSL=false
        username: gerp
        password: wcyGke4tWDRxiBdsp2b6TAfzNrL123Fn
        port: 3306
  redis:
    host: 118.190.71.200
    port: 6381
    password: abcdfu5Ymkr8KihRXcGzeqPxjAot9L7np
    database: 14

mq:
    config:
        exchange: car.direct
        queue:
            send: car.send
            send.routing.key: car.send.routing.key
            cancel: car.cancel
            cancel.routing.key: car.cancel.routing.key
            ready: car.ready
            ready.routing.key: car.ready.routing.key


wx:
  appid: wx0e36f3629b4822e2
  secret: 08162a25e3d76066c5f14af2479b459a
  templateId: yGkGgR0u3nj1X5p6ZfamN2fMc9ts4hDUyjHDd6hEQ1k