spring:
  rabbitmq:
     host: 192.168.9.100
     port: 5672
     username: reindex
     password: reindex
     listener:
       simple:
         retry:
           enabled: true
           max-attempts: 5

  datasource:
    hikari:
      st:
        name: st
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.9.100:3306/tongyun_mes?useSSL=false
        password: fhieukzjdhwuieurwuiery19dakjdJHNMJQ
        username: gerp_mes
        port: 3306
      jh:
        name: jh
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.9.45:3306/tongyun_mes?useSSL=false
        password: tongyun2017
        username: shengtian
        port: 3306
      sd:
        name: sd
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.9.32:3306/tongyun_mes?useSSL=false
        username: shengtian
        password: evMyV0X5EhlPS4545BmaNYmE
        port: 3306
      sda:
        name: sd
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.100:3306/tongyun_mes?useSSL=false
        username: shengtian
        password: evMyV0X5EhlPS4545BmaNYmE
        port: 3306
  redis:
    host: 192.168.9.100
    port: 6379
    password: wP35CBv7HrxyYDkfeqUqbfKSMcsQWoXNT
    database: 14

mq:
    config:
        exchange: car.direct
        queue:
            send: car.send
            send.routing.key: car.send.routing.key
            cancel: car.cancel
            cancel.routing.key: car.cancel.routing.key
            ready: car.ready
            ready.routing.key: car.ready.routing.key


wx:
  appid: wx0e36f3629b4822e2
  secret: 08162a25e3d76066c5f14af2479b459a
  templateId: yGkGgR0u3nj1X5p6ZfamN2fMc9ts4hDUyjHDd6hEQ1k