spring:
  datasource:
    hikari:
      st:
        name: st
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/st?useSSL=false
        password: 123456
        username: root
        port: 3306
      jh:
        name: jh
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/jh?useSSL=false
        password: 123456
        username: root
        port: 3306

wx:
  appid: wx0e36f3629b4822e2
  secret: 08162a25e3d76066c5f14af2479b459a